### ISSUE TITLE
Quarantine

### ISSUE THREAD

**Issue by sLairT** [patrickl92/AudioChecklist#13]
Maybe I am not doing something right, I keep getting the scripts quarantined? Any suggestions?
Thanks

**Comment by patrickl92** [comment]
I guess that the Modules folder was not copied correctly. The folder structure should look like this:

FlyWithLua
├── Modules
│  └── audiochecklist
│     ├── audio.lua
│     └── ...
└── Scripts
   ├── AudioChecklists
   │  ├── B737_SAS _(if installed)_
   │  └── B737_ZiboDefault _(if installed)_
   ├── AudioChecklist.lua
   ├── AudioChecklist_B737_SAS.lua _(if installed)_
   └── AudioChecklist_B737_ZiboDefault.lua _(if installed)_

**Comment by sLairT** [comment]
Maybe it's not for me. I am apologies but it just keeps sending the stuff to quarantine, is there anything else I need to make this work? Maybe I am missing something? I don't get the Audio checklist show window in the Lua menu either so maybe I am definitely missing something. Thanks for your time

**Comment by patrickl92** [comment]
Can you take a screenshot of the content of the folder `<X-Plane>\Resources\plugins\FlyWithLua\Scripts\` and `<X-Plane>\Resources\plugins\FlyWithLua\Modules` and upload them here, so that I can see what is in there?

**Comment by sLairT** [comment]
This is a snip of the folders with the scripts removed
[image: modules.jpg]
[image: scripts.jpg]

**Comment by patrickl92** [comment]
Unfortunatly, I can't see your images. Please open the GitHub page and post the images there: https://github.com/patrickl92/AudioChecklist/issues/13

**Comment by patrickl92** [comment]
@sLairT Have you solved your issue?

**Comment by sLairT** [comment]
Oh just today I realised I haven't sent your request. Thanks for the prompt
real life has got a bit hectic. will send today at some point!

**Comment by sLairT** [comment]
Here are the images.

![scripts](https://user-images.githubusercontent.com/100177474/157505668-c7314f65-fd8e-4c99-b24d-484f6eb0643b.jpg)
![modules](https://user-images.githubusercontent.com/100177474/157505678-05631144-55d5-404f-a1bd-c4768a6e3cb8.jpg)

**Comment by sLairT** [comment]
Scripts file first files first and the modules in the second jpeg.

**Comment by patrickl92** [comment]
Thank you. In the second image, there should be a folder called `audiochecklist`. It is located in the `Modules` folder of the downloaded ZIP file.

This should be the content of that folder:

![grafik](https://user-images.githubusercontent.com/16118262/157737896-b2ac6cfe-c4dc-4eb3-9891-5e2552149551.png)

After you have copied that folder to the `Modules` folder of FlyWithLua, move the quarantined files back to the `Scripts` folder and try again.

**Comment by sLairT** [comment]
Ok, give me 2 days to try...IRLis winning at the moment. I appreciate your
help.

Regards,
sLairT

**Comment by sLairT** [comment]
Hey,
Got back to it, didn't work. I am at a loss...I have included screenshots hopefully it can shed light on my ignorance. I will wait for your response.
![scripts](https://user-images.githubusercontent.com/100177474/158041832-6a09ecbb-e4ce-4ffd-b8bd-991a14e06b42.jpg)
![modules](https://user-images.githubusercontent.com/100177474/158041836-e1b473cb-b23a-47ed-8d44-3f587a5d0ff0.jpg)
![audioclist](https://user-images.githubusercontent.com/100177474/158041839-d4a6f465-a464-4278-a024-52fd1e46ace5.jpg)
![quar](https://user-images.githubusercontent.com/100177474/158041841-0d8d3f01-20e1-46b9-9648-c582ce950206.JPG)
![menu](https://user-images.githubusercontent.com/100177474/158041844-76e4544a-0172-4027-914c-d293204fbd0e.JPG)

**Comment by sLairT** [comment]
Also included the two zibo mods I choose
![planes](https://user-images.githubusercontent.com/100177474/158041987-13e4380d-0539-4b4a-9661-7ac56351cf5c.JPG)

**Comment by sLairT** [comment]
This is driving me batty!! lol. I watched this guy do everything I did, but mind still doesn't work...lol
https://www.youtube.com/watch?v=wyubZvbYXCc&ab_channel=SIM2HEAVEN

**Comment by prokopiu** [comment]
> Hey,
> Got back to it, didn't work. I am at a loss...I have included screenshots hopefully it can shed light on my ignorance. I will wait for your response.
> ![menu](https://user-images.githubusercontent.com/100177474/158041844-76e4544a-0172-4027-914c-d293204fbd0e.JPG)

In the FlyWithLua menu activate the “Disable moving bad scripts to Quarantine”. Then get the 2 Audio....lua in Scripts (Quarantined) back to Scripts folder. Then use “Reload all Lua scripts files. You should now either get an error shown at the top of X-Plane which you can send us as screenshot or you will see a red Lua stopped at the top right.

In any case, there is a log.txt in the X-Plane root folder which should contain FlyWithLua errors to use for analysis at the end of the file. This will help to catch your problem.

It is important that you use the latest FlyWithLua plugin. There was an update recently on the forum.

And what Zibo version are you using? Did you set any options in the EFB which differ from the vanilla settings the Zibo comes with OOTB?

Let’s see if we can catch that one 😊

**Comment by sLairT** [comment]
Great news!!
I updated LUA and ZIBO Mod to the latest versions and like magic when I started XP11 and loaded in! it all WORKS!! Thank you Patrick for your patience and Proko for additional support on this. Now next challenge to fly the thing....lol!! Tested all the checklist items and they are all working. Happy programming!! Looking forward to improvements on this product.

**Comment by patrickl92** [comment]
Awesome! Happy flying!
Thank you @prokopiu for your hints.

**Comment by sLairT** [comment]
Guys here is a stream of me using the software!! it's really helpful and
fun!!
https://youtu.be/xiUU2zaffQs
Thanks for your help and continued support.

sLairT
