### ISSUE TITLE
Audio checklist problem

### ISSUE THREAD

**Issue by gilby737** [patrickl92/AudioChecklist#14]
Hi,
Audiochecklist is not showing up in Lua, Macro.
I think i installed al the files and Sop in the correct folders.
Can you help please?
Kind regards,
Gilbert.

**Comment by patrickl92** [comment]
Hi Gilbert,
can you take a screenshot of the content of the folder `<X-Plane>\Resources\plugins\FlyWithLua\Scripts\` and `<X-Plane>\Resources\plugins\FlyWithLua\Modules` and upload them here, so that I can see what is in there?

**Comment by gilby737** [comment]
[image: image.png][image: 56408d3e-a6b6-4be9-b664-a1789ca7c3a4.png][image:
image.png][image: image.png]

Patrick,
Thanks for your reply.
Strange thing is that I have in the resources map a plugging map, but
inside the plugins map which is above the resources map there is another
plugin map.
I already deleted that plugin map, but no results.
When I started x plane 11, there was nothing in the plugins, no LUA, no
other addons like for example better pushbak, x camera etc.....
Sorry sending you my problems,
Kind regards,
Gilbert.






Op do 31 mrt. 2022 om 19:49 schreef Patrick Lang ***@***.***>:

**Comment by gilby737** [comment]
Hi Patrick,

the problem is solved, I deleted the resources map, and let x plane build a
new one.
Reinstalled FLY WITH LUA,
Thanks,
Gilbert.


Op do 31 mrt. 2022 om 19:49 schreef Patrick Lang ***@***.***>:

**Comment by gilby737** [comment]
[image: image.png][image: image.png][image: image.png]

Patrick,
These are the prints of the audi checklist in Lua,
In plugins , Lua, Macros. I still can't see my audio checklist.
Kind regards,
Gilbert.


Op vr 1 apr. 2022 om 00:00 schreef gilbert Goossens ***@***.***>:

**Comment by patrickl92** [comment]
Hi Gilbert, I can't see you images. Please open this link and post the images there: https://github.com/patrickl92/AudioChecklist/issues/14

**Comment by gilby737** [comment]
Hi Patrick,

I solved the problem.
Thank you for youre reply.
Kind regards,
Gilbert.

Op di 5 apr. 2022 10:04 schreef Patrick Lang ***@***.***>:
