### ISSUE TITLE
Empty drop down menus

### ISSUE THREAD

**Issue by gresol** [patrickl92/AudioChecklist#15]
EDIT
Sorry, I just found out what caused my mistake.

However could you please make it clearer that SOPs must be downloaded separately…

thank you!

**Comment by patrickl92** [comment]
I've added an additional message which is shown if there are no SOPs for the selected plane. It also brings you directly to the correct GitHub page to download them:

![grafik](https://user-images.githubusercontent.com/16118262/170826648-7eb1eca0-6a18-4674-a5aa-bacacd735b8f.png)
