### ISSUE TITLE
XP 12 is not supported

### ISSUE THREAD

**Issue by keremers** [patrickl92/AudioChecklist#17]
Hi,

Today FlyWithLua released for XP12. But Audio Checklist is immediately quarantined. XP 12 version required.

**Comment by patrickl92** [comment]
Hi, i have tried it with the FlyWithLua version for X-Plane 12 and it worked. Can you please provide the X-Plane log file?

**Comment by keremers** [comment]
Dear Patrick,

You are right. I believe my previous installation was an older version of AudioChecklist this is why they were quarantined. A check into FlyingwithLua quarantine folder revealred that the auidoChecklstPlugin I've installed was dated February not May ias it should be. Now it is working and functional I've reinstalled the latest version. Sorry for alerting you.

**Comment by patrickl92** [comment]
No need to apologize. I'm glad you could solved it.
