### ISSUE TITLE
Audiochecklist

### ISSUE THREAD

**Issue by gilby737** [patrickl92/AudioChecklist#2]
Hi,
I had installed the audiochecklist,following the manual step by step, also instald the Sop file.
Bud when i go to plugins,lua,marco i dont see any audiochecklist in here.
What could be the issue?
Sorry for my poor English.
Kind regards,
Gilbert.

**Comment by patrickl92** [comment]
Hi,
can you take a screenshot of the content of the folder `<X-Plane>\Resources\plugins\FlyWithLua\Scripts\` and `<X-Plane>\Resources\plugins\FlyWithLua\Modules` and upload them here, so that I can see what is in there?

**Comment by gilby737** [comment]
Hi Patrick,
First thank you for the quick support , i wil do this and send you the pics
asap tomorrow.
Thanks in advanced
Gilbert.

Op do 20 jan. 2022 19:15 schreef Patrick Lang ***@***.***>:

**Comment by gilby737** [comment]
Hello Patrick,

i send you the two files.
I am also using the latest FLYLUA version.
Info: beside the scripts file i have also a Scripts (quarantine) and a
Scripts (disabled ) file.
Gilbert.
 Scripts.zip
<https://drive.google.com/file/d/1GJyij-PdK53nSDFiyE6E84rMqW78dzn8/view?usp=drive_web>


Op do 20 jan. 2022 om 19:15 schreef Patrick Lang ***@***.***>:

**Comment by patrickl92** [comment]
Hi Gilbert, I don't have access to the Google Drive and I don't want to request access with my private Google account. Is is possible to attach the screenshots here? Please also look into the `Scripts (quarantine)` folder and let me know if there are any files in there.

**Comment by gilby737** [comment]
Sorry for that,
I send you tomorrow screenshots of the files.
Sorry to bother you whit my problem, i am 66 and Lua script is like Chinees
for me..😉
There is no hurry , its also weekend for you.
Gilbert.

Op vr 21 jan. 2022 18:40 schreef Patrick Lang ***@***.***>:

**Comment by gilby737** [comment]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
Hi Patrick,
I hope that print screens could help you, there are NO scripts in
quarantine.
Have a nice weekend.
Gilbert.

Op vr 21 jan. 2022 om 18:40 schreef Patrick Lang ***@***.***>:

**Comment by patrickl92** [comment]
It seems like that if you respond to the issue using E-Mail, it does not include the attached files. Please try to open the issue in the browser and then attach the files when writing a new comment.
Also, no need to apologize, I'm happy to help!

**Comment by gilby737** [comment]
Hi Patrick,
Do you mean you didn´t receive the print screens in my previous mail?
Rgds
Gilbert

Op za 22 jan. 2022 16:47 schreef Patrick Lang ***@***.***>:

**Comment by gilby737** [comment]
> Hi Gilbert, I don't have access to the Google Drive and I don't want to request access with my private Google account. Is is possible to attach the screenshots here? Please also look into the `Scripts (quarantine)` folder and let me know if there are any files in there.



> [image: image.png] [image: image.png] [image: image.png] [image: image.png] Hi Patrick, I hope that print screens could help you, there are NO scripts in quarantine. Have a nice weekend. Gilbert. Op vr 21 jan. 2022 om 18:40 schreef Patrick Lang ***@***.***>:
> […](#)
> Hi Gilbert, I don't have access to the Google Drive and I don't want to request access with my private Google account. Is is possible to attach the screenshots here? Please also look into the Scripts (quarantine) folder and let me know if there are any files in there. —

**Comment by patrickl92** [comment]
When you are responding to the GitHub notification email, I don't receive that email. Instead, your response gets added to the issue you created: https://github.com/patrickl92/AudioChecklist/issues/2

Is just seems that GitHub does not add the attachments to the issue, so please click on the link above and create a new comment, which will allow you to attach files.

**Comment by gilby737** [comment]
![image](https://user-images.githubusercontent.com/75685419/150653555-03be27ad-4a25-41c1-9e8e-9e5956f42a4b.png)
![image](https://user-images.githubusercontent.com/75685419/150653567-de2ba027-44a6-4e07-974b-3b9abdf4e247.png)
![image](https://user-images.githubusercontent.com/75685419/150653578-78265aca-8b0c-4da6-88c7-8cfc2297508f.png)

**Comment by gilby737** [comment]
Patrick,
i hope you received the files now.
Kind regards,
Gilbert.

**Comment by gilby737** [comment]
Hi Patrick,

I just sent you the 3 files, I hope its ok now.
Kind regards,
Gilbert


Op za 22 jan. 2022 om 20:47 schreef Patrick Lang ***@***.***>:

**Comment by patrickl92** [comment]
Yes, now it worked. I also spotted the mistake. You should have copied the content of the `Scripts` folder to the FlyWithLua folder, but instead you copied the folder itself.

![grafik](https://user-images.githubusercontent.com/16118262/150653946-ea1b1dcb-0d12-44c2-9e50-49b2964320ff.png)

**Comment by gilby737** [comment]
OK,
I will check and change it tomorrow and let you now something then.
I hope i didn't give you a heart attack!
Thank you so much for the support, LUA is very new for me, i am a 66 old men.......
Gilbert.

**Comment by patrickl92** [comment]
No worries, just let me know if it works afterwards.

**Comment by gilby737** [comment]
Will do, thanks!

Op za 22 jan. 2022 om 21:23 schreef Patrick Lang ***@***.***>:

**Comment by gilby737** [comment]
Hi Patrick,
I am so happy to let you now that Audiochecklist is working perfect now!
Many many thanks for you're patience and support.
Where do you life? We are living in Spain for 3 years now, but before  in Belgium.
Can i make a contribution via PayPal for a drink?
Kind regards,
Gilbert.

**Comment by patrickl92** [comment]
Hi Gilbert, I'm glad to headr you have solved it :).
I'm living in Austria. I appreciate any support using PayPal, thank you very much!

**Comment by gilby737** [comment]
Patrick,
What is youre name on Paypal,please?

Op zo 23 jan. 2022 13:36 schreef Patrick Lang ***@***.***>:

**Comment by patrickl92** [comment]
There is a donation button on the main page: https://github.com/patrickl92/AudioChecklist

**Comment by gilby737** [comment]
Thanks, I'll check it out.

Op zo 23 jan. 2022 14:29 schreef Patrick Lang ***@***.***>:

**Comment by gilby737** [comment]
Just donet,

Once again many thanks Patrick.

Op zo 23 jan. 2022 14:29 schreef Patrick Lang ***@***.***>:

**Comment by patrickl92** [comment]
Very generous of you, thank you very much

**Comment by gilby737** [comment]
You're welcome!

Op zo 23 jan. 2022 15:01 schreef Patrick Lang ***@***.***>:
