### ISSUE TITLE
No sound output

### ISSUE THREAD

**Issue by DChap1** [patrickl92/AudioChecklist#3]
Hey There. I downloaded the checklist, installed the ZIBO SOP, and can select it, the PF and PM in the SOP, but when i run a checklist, there is no audio. The settings volume is 100%.

**Comment by patrickl92** [comment]
Hi, can you provide the log file from X-Plane? It is located in the X-Plane directory, named `Log.txt`.
Start X-Plane and run a checklist. After that, close X-Plane and upload the log file here.

**Comment by DChap1** [comment]
[Log.txt](https://github.com/patrickl92/AudioChecklist/files/7914427/Log.txt)

Thanks for taking a look Patrick

**Comment by patrickl92** [comment]
According to the log file, the audio files are not at the correct location. Did you also copy the folder `AudioChecklists` from the SOP zip file to the Scripts folder?

**Comment by DChap1** [comment]
that was it. I had missed adding the voices folder to the scripts folder. Thanks Patrick. Tested it and it works.
