### ISSUE TITLE
Redundant sound when on blocks

### ISSUE THREAD

**Issue by npv1459** [patrickl92/AudioChecklist#6]
After the same flight on the issue that i have opened previously, i found another problem when on blocks (zibo 737-800)
I don't know if it could be replicated only when you are on blocks or it's releated on every flight phase.
Anyway, there is a redundant checklist readback of some items like speedbrakes and other stuff of various checklist.
Below a workaround that i found to stop this redundant sounds.. 
Open every single checklist to start and pause them
Below the xplane log attached
[Log.txt](https://github.com/patrickl92/AudioChecklist/files/7913091/Log.txt)

**Comment by patrickl92** [comment]
I've just publish a new release, which allows you to enable debug loggin using the menu entry `Plugins > FlyWithLua > FlyWithLua Macros > Audio Checklist: Enable Debug Logging`. Please download this release and activate this option before starting the SOP. Do your flight as normal and if you encounter the problem again, please upload the X-Plane log file here. It is located in the X-Plane directory, named `Log.txt`.

Note that the debug logging will always be disabled per default when starting X-Plane or selecting another aircraft.

**Comment by npv1459** [comment]
> I've just publish a new release, which allows you to enable debug loggin using the menu entry `Plugins > FlyWithLua > FlyWithLua Macros > Audio Checklist: Enable Debug Logging`. Please download this release and activate this option before starting the SOP. Do your flight as normal and if you encounter the problem again, please upload the X-Plane log file here. It is located in the X-Plane directory, named `Log.txt`.
> 
> Note that the debug logging will always be disabled per default when starting X-Plane or selecting another aircraft.

Did a new flight with the debug loggin enabled.. I made also a couple of short video with the redundant sounds...
It Also happens that, for some reasons, checklist and sounds are not syncronized.
Here you can download the video's https://we.tl/t-w8lMDFHan9
[Log.txt](https://github.com/patrickl92/AudioChecklist/files/7919499/Log.txt)

**Comment by patrickl92** [comment]
Thank you for the video, that helped me to understand what is going on. According to the log file, X-Plane has issues with loading the sound files. The files are all in the correct location, but there seems to be an internal issue. I haven't found any information on this yet, but I'll keep looking.

**Comment by patrickl92** [comment]
Sorry for the delay. I had a talk with the FlyWithLua developer and he also does not know the cause of the issue on your system. However, he had an idea of what you can try. After loading the airplane in X-Plane, before you do anything else, go to the menu and reload all Lua scripts using the menu entry `Plugins > FlyWithLua > Reload all Lua scripts`. After that, try to use the checklist extension and see if the sounds are now correct.

**Comment by patrickl92** [comment]
@npv1459 Does this issue still exists on your system?

**Comment by npv1459** [comment]
> @npv1459 Does this issue still exists on your system?

Hi patrick....sorry but i didn't had enough time to test again your plug-in... I'm confident to test it tomorrow, but as i remember, i did your suggestion, to reload all lua scripts, before opening this issue. 
As i say before, tomorrow i will try again with the latest zibo version e your lates plug-in version
Cheers

**Comment by patrickl92** [comment]
Closed due to inactivity
