### ISSUE TITLE
No Sound after installing

### ISSUE THREAD

**Issue by Langers87** [patrickl92/AudioChecklist#7]
Hi Patrick, Great Second name BTW lol.   You have a great programme here but i can't hear the checklist being read. I've followed the instructions but I'm not sure where I've went wrong. Hope you can help. Thanks again.

**Comment by patrickl92** [comment]
Hi, can you provide the log file from X-Plane? It is located in the X-Plane directory, named `Log.txt`.
Start X-Plane and run a checklist. After that, close X-Plane and upload the log file here.

**Comment by Langers87** [comment]
Patrick,

Thanks for your reply. I think i managed to solve the issue. I didnt have the folder with the voices in the correct place.

**Comment by patrickl92** [comment]
Perfect, thank you for letting me know
